boluaishu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page.urls', namespace='page'))
]

page/urls.py
from django.urls import path
from . import views 

app_name='page'

urlpatterns = [
    path('', views.home, name='home'),
    path('ceramic', views.ceramic, name='ceramic'),
    path('sculpture', views.sculpture, name='sculpture'),
    path('painting', views.painting, name='painting'),
    path('textile', views.textile, name='textile'),
    path('graphics', views.graphics, name='graphics'),
]

page/models.py
from django.db import models

# Create your models here.

page/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')

def textile(request):
    return render(request, 'textile.html')

def graphics(request):
    return render(request, 'graphics.html')

def sculpture(request):
    return render(request, 'sculpture.html')

def painting(request):
    return render(request, 'painting.html')

def ceramic(request):
    return render(request, 'ceramic.html')

page/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title  %}{% endblock %}</title>
    <link href="{% static 'index.css' %}" rel='stylesheet' type="text/css" >
    <link href="{% static 'favicon.ico' %}" type="image/ico" rel="shortcut icon">
</head>
<body>
    <main>
        {% block content %}{% endblock %}
    </main>
    <script type="text/javascript">
        (function () {
        var button = document.getElementById('toggle-menu');
            button.addEventListener('click', function (event) {
                event.preventDefault();
                var menu = document.getElementById('main-menu');
                menu.classList.toggle('is-open');
            })
        })();
    </script>
</body>
</html>

page/templates/ceramic.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Ceramic{% endblock %}

{% block content %}
<div class="ceramics" >
    <h2>Ceramics</h2>
</div>
<section class="card">
    <img src="{% static 'c_moremi.jpeg' %}">
    <div class="container">
    <h4>Name</h3>
    <p>Ibrahim Adedeji</p>
    <h4>Title:</h3>
    <p>Moremi | let there be light</p>
    <h4>Description:</h3>
    <p>Depict these picture to reflect how moremi stood her ground to save her people from darkness of ugbo
    warriors</p>
    </div>
</section>
<section class="card">
    <img src="{% static 'c_engo.jpeg'%}">
    <div class="container">
    <h3>Name:</h3><p>Olawuyi John Damilar</p>
    <h3>Title:</h3><p>Engobe((colour slip) on Malteser vase</p>
    </div>
</section>
<section class="card">
    <img src="{% static 'c_power.jpeg'%}">
    <div class="container">
    <h3>Name:</h3><p>Richard Adewale Oredola</p>
    <h3>Title:</h3><p>Power, Unity, Selflessness</p>
    <h3>Description:</h3><p>A lot can be done when we are United, and alot can destroy when we misapply the power</p>
    </div>
</section>
<section class="card">
    <img src="{% static 'c_ibrahim.jpeg' %}">
    <div class="container">
    <h3>Name:</h3><p>Ibrahim Adedeji</p>
    <h3>Title:</h3><p>Ologbon ni olode(a hunter is a wise man).</p>
    <h3>Description:</h3><p>Trapping and killing of animal in the bush requires a level of certain skill hence the title.</p>
    <h4>Medium:</h4><p>Red clay</p>
    </div>
</section>
<section class="card">
    <img src="{% static 'c_opon.jpeg' %}">
    <div class="container">
    <h4>Name:</h4><p>Arike Alamo</p>
    <h4>Title:</h4><p>Opon ifa</p>
    <h4>Description:</h4><p>This is an assemblage pot called Opon ifa. Opon ifa is an ancient sacrilege tray used for divination by the yoruba to make consultation and to get sollutions to problems</p>
    </div>
</section>
{% endblock %}

page/templates/graphics.html
{% extends 'base.html' %}
{% load static %}
{% block title %}graphics{% endblock %}

{% block content %}
<div class="graphics">
    <h2>Graphics</h2>
</div>
<section>
   <div class="card">
    <img src="{% static 'g_man.jpg' %}"> 
    <div class="container">
    <h3>untitle</h3>
    <p>Mannequin on a Dress</p>
</div>
</div>
</section>
<section>
    <div class="card">
    <div class="container">
    <img src="{% static 'lautech_clock.jpeg' %}">
    <h3>Lautech Digital Souvenir Clock (2023)</h3>
</div>
</div>
</section>
{% endblock %}

page/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home | Department Gallery {% endblock %}

{% block content %}
<div class="center_logo">
    <img class='main_logo' src="../static/logo.jpg">
</div>
<header id="header" class="page-header">
    <div class="title">
        <h1 "><a style="color: #efcc83;" href="{% url "page:home" %}">Department Gallery</a></h1>
        <div class="slogan">Bolu Ahisu's project</div>
    </div>
</header>
<nav class="menu" id="main-menu" </nav>
    <button class="menu-toggle" id="toggle-menu">
        toggle menu
    </button>
    <div class="menu-dropdown">
        <ul class="nav-menu">
            <li><a href="{% url "page:ceramic" %}">ceramic</a></li>
            <li><a href="{% url "page:sculpture" %}">sculpture</a></li>
            <li><a href="{% url "page:graphics" %}">graphics</a></li>
            <li><a href="{% url "page:textile" %}">textile</a></li>
            <li><a href="{% url "page:painting" %}">painting</a></li>
        </ul>
    </div>
</nav>
<aside id="hero" class="hero">
    Welcome to the department of fine art gallery collection!
    Where we showcase case the exception talent of the students.
</aside>

<main id="main">
    <div class="row">
        <section class="column">
            <h2 class="subtitle">Services</h2>
            <div class="mini_grid"</div>
                <div class='card' style="background-color: brown;">
                <span class="column">
                    <a href="{% url "page:textile" %}"><img src="./../static/textile.jpg"></a>
                    <div class="container" style="color: white; font-size: 1.5rem"">
                        textile
                    </div>
                </span>
                </div>
                <div class='card' style="background-color: brown;">
                <span class="column">
                    <a href="{% url "page:ceramic" %}"><img src="./../static/cermics.jpg"></a>
                    <div class="container"style="color: white; font-size: 1.5rem"">
                        ceramic
                    </div>
                </span>
                <div class='card'>
                <span class="column" style="background-color: brown;">
                    <a href="{% url "page:painting" %}"><img src="./../static/painting.jpg"></a>
                    <div class="container"style="color: white; font-size: 1.5rem">
                        painting
                    </div>
                </span>
                </div>
                <div class='card' style="background-color: brown;">
                <span class="column">
                    <a href="{% url "page:sculpture" %}"><img src="./../static/s_metalic.jpg"></a>
                    <div class="container"style="color: white; font-size: 1.5rem"">
                        sculpture
                    </div>
                </span>
                <div class='card' style="background-color: brown;">
                <span class="column">
                    <a href="{% url "page:graphics" %}"><img src="./../static/graphics.jpg"></a>
                    <div class="container"style="color: white; font-size: 1.5rem"">
                        graphics
                    </div>
                </span>
                </div>
        </section>
        <section class="column">
            <h2 class="subtitle">About</h2>
            <p>Ahisu Boluwatife Sesede, Matric Number 183891</p>
            <p>Computer Art project supervised by Mr.Oyeyode</p>
        </section>
    </div>
</main>
{% endblock %}

page/templates/painting.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Painting{% endblock %}


{% block content %}
<div class="painting">
    <h2 style="color: brown;">Painting</h2>
</div>
<section>
    <div class="card">
    <img src="{% static 'p_motherslove.jpg' %}">
    <div class="container">
    <h3>Artist:</h3><p>Oyedale Abiodun Oyewumi</p>
    <h3>Title:</h3><p>undying Love</p>
    <h3>Date: </h3><p>2022</p>
    <h3>Size:</h3><p>60 x 48 inches</p>
    <h3>Story: </h3><p>A mother's love for her child is like nothing else in the world. It knows no law, no pity. it dares all things and crushes down remoreselessly all that stands in its path.</p>
    </div>
    </div>
</section>
<section>
    <div class="card">
    <img src="{% static 'p_festival.jpeg' %}">
    <div class="container">
    <h3>Artist:</h3><p>Popoola Fikayo Olamide</p>
    <h3>Title:</h3><p>festival</p>
    <h3>Date: </h3><p>2022</p>
    <h3>Size:</h3><p>3 by 4ft</p>
    </div>
    </div>
</section>
<section>
    <div class="card">
    <img src="{% static 'p_similingperson.jpg' %}">
    <div class="container">
    <h3>Artist:</h3><p>Patience Adekunle</p>
    <h3>Title:</h3><p>the unco Essence</p>
    <h3>Date: </h3><p>2022</p>
    <h3>Size:</h3><p>60 x 66</p>
</section>
<section>
    <div class="card">
    <img src="{% static 'p_iyaniwura.jpg' %}">
    <div class="container">
    <h3>Artist:</h3><p>Akintunde Emmanuel (Tbeny)</p>
    <h3>Title:</h3><p>Iya Ni Wura</p>
    <h3>Date: </h3><p>2020</p>
    <h3>Size:</h3><p>60 x 66</p>
    <h3>Technique:</h3><p>Impasto</p>
    <h3>Medium:</h3><p>oil on canvas</p>
</div>
</div>
</section>
{% endblock %}

page/templates/sculpture.html
{% extends 'base.html' %}
{% load static %}
{% block title %}sculpture{% endblock %}

{% block content %}
<div class="sculpture">
    <h2>Sculpture</h2>
</div>
<section>
    <div class="card">
    <img src="{% static 's_transedence.jpg' %}">
    <div class="container">
    <h4>Name</h4><p>Toye Ayomide</p>
    <h4>Title</h4><p>Transcendence</p>
    <h4>Medium</h4><p>Metal nut, metal plate</p>
</div>
</div>
</section>
<section>
    <div class="card">
    <img src="{% static 's_metalic.jpg' %}">
    <div class="container">
    <h4>Name</h4><p>Akanbi Damola Joshua</p>
    <h4>Title</h4><p>ORI(head)</p>
    <h4>Medium</h4><p>scrap metal</p>
    </div>
</div>
</section>
<section>
    <div class="card">
    <img src="{% static 's_clay.jpeg' %}">
    <div class="container">
    <h4>Name</h4><p>Joseph Opeyemi Adegbenjo</p>
    <h4>Title</h4><p>Beautiful</p>
    <h4>Medium</h4><p>clay</p>
    <h4>Year</h4><p>2022</p>
</div>
</div>
</section>
<section>
    <div class="card">
    <img src="{% static 's_hammer.jpg' %}">
    <div class="container">
    <h4>Name</h4><p>olamide abraham</p>
    <h4>Title</h4><p>Stone breaker</p>
    <h4>Medium</h4><p>Junk metal</p>
</div>
</div>
</section>
<section>
    <div class="card">
    <img src="{% static 's_wood.jpeg' %}">
    <div class="container">
    <h4>Name</h4><p>Akanbi Damola j</p>
    <h4>Title</h4><p>A tale of two couples and their unborn children</p>
    <h4>Medium</h4><p>wood fastener and chains</p>
</div>
</div>
</section>
<section>
    <div class="card">
    <img src="{% static 's_ariya.jpeg' %}">
    <div class="container"
    <h4>Name</h4><p>Isaac Oluwaseyi Ajani</p>
    <h4>Title</h4><p>Ariya</p>
    <h4>Year</h4><p>2021</p>
</div>
</div>
</section>
{% endblock %}

page/templates/textile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}textile{% endblock %}

{% block content %}
<div class="textile">
    <h2>Painting</h2>
</div>
<section>
    <img src="{% static 't_acry.jpeg' %}">
    <h4>Name</h4><p>Ojerinde olayemi</p>
    <h4>Size</h4><P>3ft by 7ft</P>
    <h4>Medium</h4><p>Acrylic</p>
</section>
<section>
    <img src="{% static 't_embroidery.jpeg' %}">
    <h4>Name</h4><p>Omisakin F.taiwo</p>
    <h4>Medium</h4><p>Embroidery(wool)</p>
    <h4>Size</h4><p>3ft by 7ft</p>
</section>
<section>
    <img src="{% static 't_bead.jpeg' %}">
    <h4>Name</h4><p>kukoyi</p>
    <h4>Medium</h4><p>Bead on Hard Board</p>
    <h4>Size</h4><p>3ft by 4ft</p>
</section>
{% endblock %}